version: '3.5'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
    command: etcd -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379

  milvus:
    image: milvusdb/milvus:v2.3.9
    container_name: milvus
    depends_on:
      - etcd
    ports:
      - "19530:19530"
      - "19121:19121"
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MILVUS_LOG_LEVEL: debug
      MILVUS_ENABLE_PROFILING: "false"
      MILVUS_DEFAULT_DB_NAME: default
